version: 2

builds:
  - main: .
    dir: ./cmd/blink
    binary: blink
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - blink.toml.example

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
